# Site settings
baseurl: ""

# These are overridden by Github. They're here for local rendering
github:
  project_title: Pathminder
  repository_url: https://github.com/pathminder/pathminder.github.io
  issues_url: https://github.com/pathminder/pathminder.github.io/issues

gem:
  - jekyll-sitemap

exclude:
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: afflictions
    values:
      layout: affliction
  - scope:
      path: ""
      type: alchemist-discoveries
    values:
      layout: class-talent
  - scope:
      path: ""
      type: base-classes
    values:
      layout: class
  - scope:
      path: ""
      type: blade-skills
    values:
      layout: class-talent
  - scope:
      path: ""
      type: bushido
    values:
      layout: class-talent
  - scope:
      path: ""
      type: descriptors
    values:
      layout: descriptor
  - scope:
      path: ""
      type: equipment
    values:
      layout: equipment
  - scope:
      path: ""
      type: evolutions
    values:
      layout: evolution
  - scope:
      path: ""
      type: feat-types
    values:
      layout: feat-type
  - scope:
      path: ""
      type: feats
    values:
      layout: feat
  - scope:
      path: ""
      type: magic-items
    values:
      layout: magic-item
  - scope:
      path: ""
      type: magic-item-properties
    values:
      layout: magic-item-property
  - scope:
      path: ""
      type: maneuvers
    values:
      layout: maneuver
  - scope:
      path: ""
      type: martial-disciplines
    values:
      layout: martial-discipline
  - scope:
      path: ""
      type: occult-rituals
    values:
      layout: occult-ritual
  - scope:
      path: ""
      type: prestige-classes
    values:
      layout: class
  - scope:
      path: ""
      type: races
    values:
      layout: race
  - scope:
      path: ""
      type: rage-powers
    values:
      layout: class-talent
  - scope:
      path: ""
      type: rogue-talents
    values:
      layout: class-talent
  - scope:
      path: ""
      type: rogue-advanced-talents
    values:
      layout: class-talent
  - scope:
      path: ""
      type: sources
    values:
      layout: source
  - scope:
      path: ""
      type: skills
    values:
      layout: skill
  - scope:
      path: ""
      type: spells
    values:
      layout: spell
  - scope:
      path: ""
      type: stalker-arts
    values:
      layout: class-talent
  - scope:
      path: ""
      type: tactical-presences
    values:
      layout: class-talent
  - scope:
      path: ""
      type: trait-types
    values:
      layout: trait-type
  - scope:
      path: ""
      type: traits
    values:
      layout: trait
  - scope:
      path: ""
      type: warlord-gambits
    values:
      layout: class-talent

collections:
  afflictions:
    output: true
    title: Afflictions
  alchemist-discoveries:
    output: true
    title: Alchemist Discoveries
  base-classes:
    output: true
    title: Base Classes
  blade-skills:
    output: true
    title: Blade Skills
  bushido:
    output: true
    title: Bushido
  descriptors:
    output: true
    title: Descriptors
  equipment:
    output: true
    title: Equipment
  evolutions:
    output: true
    title: Evolutions
  feats:
    output: true
    title: Feats
  feat-types:
    output: true
    title: Feat Types
  glossary-terms:
    output: true
    title: Glossary Terms
  magic-items:
    output: true
    title: Magic Items
  magic-item-properties:
    output: true
    title: Magic Item Properties
  maneuvers:
    output: true
    title: Maneuvers
  martial-disciplines:
    output: true
    title: Martial Disciplines
  occult-rituals:
    output: true
    title: Occult Rituals
  prestige-classes:
    output: true
    title: Prestige Classes
  races:
    output: true
    title: Races
  rage-powers:
    output: true
    title: Rage Powers
  rogue-talents:
    output: true
    title: Rogue Talents
  rogue-advanced-talents:
    output: true
    title: Rogue Advanced Talents
  sources:
    output: true
    title: Sources
  skills:
    output: true
    title: Skills
  spells:
    output: true
    title: Spells
  stalker-arts:
    output: true
    title: Stalker Arts
  systems:
    output: true
    title: Systems
  tactical-presences:
    output: true
    title: Tactical Presences
  trait-types:
    output: true
    title: Trait Types
  traits:
    output: true
    title: Traits
  warlord-gambits:
    output: true
    title: Warlord Gambits
