# Site settings
baseurl: ""

# These are overridden by Github. They're here for local rendering
github:
  project_title: Pathminder
  repository_url: https://github.com/pathminder/pathminder.github.io
  issues_url: https://github.com/pathminder/pathminder.github.io/issues

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: base-classes
    values:
      layout: class
  - scope:
      path: ""
      type: blade-skills
    values:
      layout: blade-skill
  - scope:
      path: ""
      type: bushido
    values:
      layout: bushido
  - scope:
      path: ""
      type: descriptors
    values:
      layout: descriptor
  - scope:
      path: ""
      type: feat-types
    values:
      layout: feat-type
  - scope:
      path: ""
      type: feats
    values:
      layout: feat
  - scope:
      path: ""
      type: magic-items
    values:
      layout: magic-item
  - scope:
      path: ""
      type: maneuvers
    values:
      layout: maneuver
  - scope:
      path: ""
      type: martial-disciplines
    values:
      layout: martial-discipline
  - scope:
      path: ""
      type: prestige-classes
    values:
      layout: class
  - scope:
      path: ""
      type: races
    values:
      layout: race
  - scope:
      path: ""
      type: rogue-talents
    values:
      layout: rogue-talent
  - scope:
      path: ""
      type: rogue-advanced-talents
    values:
      layout: rogue-talent
  - scope:
      path: ""
      type: sources
    values:
      layout: source
  - scope:
      path: ""
      type: skills
    values:
      layout: skill
  - scope:
      path: ""
      type: spells
    values:
      layout: spell
  - scope:
      path: ""
      type: stalker-arts
    values:
      layout: stalker-art
  - scope:
      path: ""
      type: tactical-presences
    values:
      layout: tactical-presence
  - scope:
      path: ""
      type: trait-types
    values:
      layout: trait-type
  - scope:
      path: ""
      type: traits
    values:
      layout: trait
  - scope:
      path: ""
      type: warlord-gambits
    values:
      layout: warlord-gambit

collections:
  base-classes:
    output: true
    title: Base Classes
  blade-skills:
    output: true
    title: Blade Skills
  bushido:
    output: true
    title: Bushido
  descriptors:
    output: true
    title: Descriptors
  feats:
    output: true
    title: Feats
  feat-types:
    output: true
    title: Feat Types
  magic-items:
    output: true
    title: Magic Items
  maneuvers:
    output: true
    title: Maneuvers
  martial-disciplines:
    output: true
    title: Martial Disciplines
  prestige-classes:
    output: true
    title: Prestige Classes
  races:
    output: true
    title: Races
  rogue-talents:
    output: true
    title: Rogue Talents
  rogue-advanced-talents:
    output: true
    title: Rogue Advanced Talents
  sources:
    output: true
    title: Sources
  skills:
    output: true
    title: Skills
  spells:
    output: true
    title: Spells
  stalker-arts:
    output: true
    title: Stalker Arts
  systems:
    output: true
    title: Systems
  tactical-presences:
    output: true
    title: Tactical Presences
  trait-types:
    output: true
    title: Trait Types
  traits:
    output: true
    title: Traits
  warlord-gambits:
    output: true
    title: Warlord Gambits
