# Site settings
baseurl: ""

# These are overridden by Github. They're here for local rendering
github:
  project_title: Pathminder
  repository_url: https://github.com/pathminder/pathminder.github.io
  issues_url: https://github.com/pathminder/pathminder.github.io/issues

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - README.md

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: blade-skills
    values:
      layout: blade-skill
  - scope:
      path: ""
      type: classes
    values:
      layout: class
  - scope:
      path: ""
      type: feat-types
    values:
      layout: feat-type
  - scope:
      path: ""
      type: feats
    values:
      layout: feat
  - scope:
      path: ""
      type: maneuvers
    values:
      layout: maneuver
  - scope:
      path: ""
      type: martial-disciplines
    values:
      layout: martial-discipline
  - scope:
      path: ""
      type: races
    values:
      layout: race
  - scope:
      path: ""
      type: rogue-talents
    values:
      layout: rogue-talent
  - scope:
      path: ""
      type: rogue-advanced-talents
    values:
      layout: rogue-talent
  - scope:
      path: ""
      type: trait-types
    values:
      layout: trait-type
  - scope:
      path: ""
      type: traits
    values:
      layout: trait

collections:
  blade-skills:
    output: true
    title: Blade Skills
  classes:
    output: true
    title: Classes
  feats:
    output: true
    title: Feats
  feat-types:
    output: true
    title: Feat Types
  maneuvers:
    output: true
    title: Maneuvers
  martial-disciplines:
    output: true
    title: Martial Disciplines
  races:
    output: true
    title: Races
  rogue-talents:
    output: true
    title: Rogue Talents
  rogue-advanced-talents:
    output: true
    title: Rogue Advanced Talents
  sources:
  trait-types:
    output: true
    title: Trait Types
  traits:
    output: true
    title: Traits
